ORG 1000H
EOI EQU 20H
IMR EQU 21H
INT0 EQU 24H
MSJ DB "CHAU"

ORG 3000H
; ESCRIBO LA SUBRUTINA DE INTERRUPCION
SALUDAR: MOV BX, OFFSET MSJ
         MOV AL, 4
         INT 7

         MOV AL, 20h
         OUT EOI, AL
         IRET

ORG 2000H
;CONFIGURAR REGISTRO IMR (HABILITO F10 LINEA 0)
MOV AL ,0FEH ; HABILITO CON 0 (1111 1110)
OUT IMR, AL

;CONFIGURAR REGISTRO INT0
;INT0 TIENE EL ID DE INTERRUPCION
MOV AL, 24 ; CUALQUIER NUMERO DE ID (24)
OUT INT0, AL

; CONFUGURAR VECTOR DE INTERRUPCIONES
; EL ID ES 24 -> LA POSICION EN EL VECTOR ES 24*4 =96

MOV BX, 96
MOV WORD PTR [BX], 3000h ; DIR DE SUBRUTINA

LOOP: JMP LOOP

INT 0
END