
ORG 1000H
PA EQU 30H
PB EQU 31H
CA EQU 32H
CB EQU 33H
Cadena DB "A"

ORG 2000H
;CONFUG PA (ESTADO) STROBE 0 BYSY 1
MOV AL, 11111101b
OUT CA, AL

; CONFIG PB (DATOS) TODOS SALIDA
MOV AL, 0
OUT CB, AL
; VERIFICAR QUE EL BUFFER NO ESTA LLENO BUSSY = 0
IN AL, PA
AND AL, 1 

MOV BX, OFFSET CADENA 
MOV AL, [BX]
OUT PB, AL ; MANDO EL CARACTER

;AVISO QUE MANDE UN CARACTER
IN AL, PA ; TOMO EL ESTADO
AND AL, 0FDH ; FUERZO STROBE 0
OUT PA, AL
OR AL ,2 ; FUERZO STROBE A 1 
OUT PA, AL



int 0
end