ORG 1000H
DATO EQU 40H
ESTADO EQU 41H
MSJ DB "INGENIERIA E INFORMATICA"
FIN DB ?

       
ORG 2000H
MOV CL, OFFSET FIN - OFFSET MSJ ;LONG CADENA
MOV BX, OFFSET MSJ
LOOP: IN AL, ESTADO ; CONSULTA DE ESTADO
      AND AL, 1 ; SI BUSSY ES 1 AL = 1 , SI BUSSY = 0 AL = 0(LIBRE)
      JNZ LOOP
      ; BUFFER LIBRE
      MOV AL, [BX]
      OUT DATO, AL ; ENVIO EL CARACTER
      INC BX ; AVANZO EN LA CADENA
      DEC CL
      JNZ LOOP
INT 0
END