ORG 1000H
    TEXTO DB "Holiwis UwU"
    FIN_TEXTO DB 00H
    VOCALES DB "AEIOUaeiou"
    FIN_VOCALES DB 00H
    CARACTER DB "Z"

ORG 3000H

; RECIBE CARACTER POR VALOR Y RETORNA
;   FFH SI ES VOCAL O
;   00H SI NO LO ES
;   POR REGISTRO
; AL -> VOCAL
; BX -> DIRECCION VOCALES
; CX -> CANTIDAD VOCALES (10)
; DX -> DIRECCION ES_VOCAL
; AH -> RETORNA
ESVOCAL: CMP CX, 0
    JZ ESVOCAL_FALSO
    CMP BYTE PTR [BX], AL
    JZ ESVOCAL_VERDADERO
    INC BX
    DEC CX
    JMP ESVOCAL
ESVOCAL_VERDADERO: MOV AH, 0FFH
    JMP ESVOCAL_FIN
ESVOCAL_FALSO: MOV AH, 00H
ESVOCAL_FIN: RET


ORG 2000H

    MOV AL, CARACTER
    MOV BX, OFFSET VOCALES
    MOV CX, OFFSET FIN_VOCALES - OFFSET VOCALES

    CALL ESVOCAL
    
    HLT
    END