ORG 1000H
    TEXTO DB "AEIOIiU"
    FIN_TEXTO DB 00h
    CARACTER DB "I"
    EQUIS DB "X"
    CANTCHAR DB 00
    

ORG 3000H
CONCAR: CMP BYTE PTR [BX], 00h
    JZ CONCAR_FIN
    CMP BYTE PTR [BX], AL
    JNZ CONCAR_NO_CONTAR
    INC DX
    MOV BYTE PTR [BX], AH
CONCAR_NO_CONTAR: INC BX
    JMP CONCAR
CONCAR_FIN: MOV BX, CX
    MOV BYTE PTR [BX], DL
    RET

ORG 2000H

    MOV AH, EQUIS
    MOV AL, CARACTER
    MOV BX, OFFSET TEXTO
    MOV CX, OFFSET CANTCHAR
    CALL CONCAR

HLT
END
