ORG 1000H
    NUM DB 00001010b
    CANTROT DB 03H
    RES DB 00000000b

ORG 3000H

; MULTIPLICAR Ax7=B
; DL -> A
; B -> DB
CALC_ROTACIONES: CMP DL,0
    JZ MUL_CERO
    MOV DH, 6; SUMA 6 VECES DL EN DL
    MOV CL, DL; GUARDA EN CL NUMERO A MULTIPLICAR
CALC_LOOP: CMP DH,0
    JZ MUL_FIN
    ADD DL, CL
    DEC DH
    JMP CALC_LOOP
MUL_CERO: MOV DH, 0
MUL_FIN: RET

; ROTA DERECHA
; RECIBE
; AL BYTE A ROTAR
; AH CANTIDAD DE ROTACIONES
; BX DIRECCION PARA GUARDAR EL RESULTADO
ROTARDER: CMP AH, 0
    JZ ROTARDER_FIN
    MOV DL, AH
    CALL CALC_ROTACIONES; RECIBE EN DL LA CANTIDAD DE ROTACIONES 
                        ; A LA IZQUIERDA NECESARIAS PARA ROTAR
                        ; CORRECTAMENTE A LA DERECHA
ROTARDER_LOOP: CMP DL, 0
    JZ ROTARDER_FIN
    ADD AL, AL
    ADC AL, 0
    DEC DL
    JMP ROTARDER_LOOP
ROTARDER_FIN:
    MOV [BX], AL
    RET

ORG 2000H
    MOV AL, NUM
    MOV AH, CANTROT
    MOV BX, OFFSET RES
    CALL ROTARDER
    HLT
    END