ORG 1000H
    DATOA DW 1234H
    DATOB DW 6789H

ORG 3000H
SWAP: PUSH BX
    MOV BX, SP
    PUSH AX
    PUSH CX
    PUSH DX
    ADD BX, 4
    MOV CX, [BX]; GUARDO EN CX LA DIRECCION DE DATOA
    ADD BX, 2
    MOV DX, [BX]; GUARDO EN DX LA DIRECCION DE DATOB

    ; GUARDO DIRECCIONES
    PUSH CX; APILO DIRECCION DE DATOA
    PUSH DX; APILO DIRECCION DE DATOB

    ; GUARDO VALORES DATOA > AX | DATOB > CX
    MOV BX, CX; GUARDO EN BX LA DIRECCION DE DATOA
    MOV AX, [BX]; GUARDO VALOR DATOA EN AX
    
    MOV BX, DX; GUARDO LA DIRECCION DE DATOB EN BX 
    MOV CX, [BX]; GUARDO VALOR DATOB EN CX

    ; GUARDO VALOR DATOA EN LA DIRECCION DE DATOB
    POP BX; DESAPILO DIRECCION DATOB EN BX
    MOV WORD PTR [BX], AX

    ; GUARDO VALOR DE DATOB EN LA DIRECCION DE DATOA
    POP BX; DESAPILO DIRECCION DATOA EN BX
    MOV WORD PTR [BX], CX
    
    POP DX
    POP CX
    POP AX
    POP BX
    RET

ORG 2000H

    MOV AX, OFFSET DATOA
    PUSH AX
    MOV AX, OFFSET DATOB
    PUSH AX
    CALL SWAP

HLT
END
