ORG 1000H
    TEXTO DB "Aleliuya diria dios SANTO miO"
    FIN_TEXTO DB 00H
    L_VOCALES DB "AEIOUaeiou"
    FIN_VOCALES DB 00H
    CANTVOCALES DB 00H

ORG 3000H

; RECIBE CARACTER POR VALOR Y RETORNA
;   FFH SI ES VOCAL O
;   00H SI NO LO ES
;   POR REGISTRO
; AL -> LETRA
; BX -> DIRECCION VOCALES
; CH -> CANTIDAD VOCALES (10)
; AH -> RETORNA
ESVOCAL: CMP CL, 0
    JZ ESVOCAL_FALSO
    CMP BYTE PTR [BX], AL
    JZ ESVOCAL_VERDADERO
    INC BX
    DEC CL
    JMP ESVOCAL
ESVOCAL_VERDADERO: MOV AH, 0FFH
    JMP ESVOCAL_FIN
ESVOCAL_FALSO: MOV AH, 00H
ESVOCAL_FIN: RET

; RECIBE TEXTO Y RETORNA CANTIDAD DE CARACTERES
; BX DIRECCION INICIO TEXTO
; CL CANTIDAD CARACTERES TEXTO
; DX DIRECCION DE LETRAS VOCALES
; CH CANTIDAD DE LETRAS VOCALES
VOCALES: CMP CL, 0
    JZ VOCALES_FIN
    MOV AL, [BX]; GUARDO EN AL EL VALOR DE LA LETRA
    PUSH BX; GUARDO ULTIMA DIRECCION DEL TEXTO COMPARADA
    MOV BX, DX; GUARDO EN BX LA DIRECCION DE LAS VOCALES
    PUSH CX; GUARDO CONTADOR DE TEXTO
    MOV CL, OFFSET FIN_VOCALES - OFFSET L_VOCALES; (10)
    CALL ESVOCAL

    POP CX; RECUPERO CONTADOR DE TEXTO
    POP BX; RECUPERO DIRECCION DE TETXO
    CMP AH, 00H
    JZ VOCALES_NO_CONTAR
    INC CH
VOCALES_NO_CONTAR: INC BX
    DEC CL
    JMP VOCALES

VOCALES_FIN: RET

ORG 2000H

    MOV BX, OFFSET TEXTO; DIRECCION DE INICIO DEL TEXTO
    MOV CL, OFFSET FIN_TEXTO - OFFSET TEXTO; CANT CARACTERES DE TEXTO
    MOV DX, OFFSET L_VOCALES
    MOV CH, CANTVOCALES

    CALL VOCALES
    
    HLT
    END