    END
ORG 1000H  
    A DW 3H 
    B DW 3H 
    TOTAL DW ?

ORG 3000H
; MULTIPLICIOCION AxB=C 
; ENVIO A Y B POR PILA
; GUARDO C EN LA DIRECCION DE MEMORIA DE TOTAL
MUL: PUSH BX
    MOV BX,SP
    PUSH AX
    PUSH CX
    PUSH DX
    ADD BX, 6
    MOV AX, [BX]; OPERADORNDO A
    ADD BX, 2
    MOV CX, [BX]; OPERANDO B
    MOV DX, 0; VALOR DE C
    
MUL_LOOP:
    CMP CX, 0
    JZ MUL_FIN
    ADD DX, AX
    DEC CX
    JMP MUL_LOOP

MUL_FIN:
    SUB BX, 4; APUNTO A LA PILA DONDE ESTA GUARDADA LA DIRECCION DE TOTAL
    MOV BX, [BX]; GUARDO EN BX LA DIRECCION DE MEMEORIA DE TOTAL
    MOV [BX], DX
    POP DX
    POP CX
    POP AX
    POP BX
    RET

ORG 2000H
    MOV AX, A
    PUSH AX
    MOV AX, B
    PUSH AX
    MOV AX, OFFSET TOTAL
    PUSH AX
    CALL MUL
    HLT
    END