ORG 1000H 
    TITULO   DB  "Ingrese Clave Privada:" 
    TITULO_FIN   DB  ? 
    CLAVE_CORRECTA DB 0AH, "[+] Acceso Permitido"
    CLAVE_INCORRECTA DB 0AH, "[-] Accseso Denegado"
    CLAVE_FIN DB ?

ORG 1500H 
    CLAVE DB "ABCD"
    PUNTO DB "*"
    DEL DB 8
    CARACTER DB ?

ORG 3000H
    CLEAN DB 12
LIMPIAR_CONSOLA: 
    PUSH BX
    PUSH AX
    MOV BX, OFFSET CLEAN
    MOV AL, 1
    INT 7
    POP AX
    POP BX
    RET

ESCONDER_CARACTER: 
    PUSH BX
    PUSH AX
    MOV BX, OFFSET DEL
    MOV AX, 1
    INT 7
    MOV BX, OFFSET PUNTO
    INT 7
    POP AX
    POP BX
    RET

CHEQUEAR_COINCIDENCIA: 

    ; BX TIENE LA DIRECCION DEL CARACTER INGRESADO
    ; CL TIENE LA POSICION DE LA CLAVE
    ; CLAVE ES LA DIRECCION DE LA PRIMER LETRA DE LA CLAVE
    ; RETORNA EN AL 00H SI NO COINCIDE O FFH SI COINCIDE
    PUSH BX
    PUSH CX
    
    CMP AL, 00H
    JZ CHEQUEAR_COINCIDENCIA_FIN

    MOV AL, 00H

    MOV AH, [BX]; GUARDO EN AH EL CARACTER INGRESADO

    MOV BX, OFFSET CLAVE
    MOV CH, 00
    ADD BX, CX; GUARDO EN BX LA DIRECCION DE LA LETRA EN CLAVE

    CMP AH, [BX]
    JNZ CHEQUEAR_COINCIDENCIA_FIN

    MOV AL, 0FFH

CHEQUEAR_COINCIDENCIA_FIN:
    POP CX
    POP BX
    RET

INGRESAR_CARACTER:     
    MOV BX, OFFSET CARACTER
    INT 6
    CALL ESCONDER_CARACTER
    CALL CHEQUEAR_COINCIDENCIA
    RET

ORG 2000H 
    CALL LIMPIAR_CONSOLA
    MOV CL, 0
    MOV BX, OFFSET TITULO 
    MOV AL, OFFSET TITULO_FIN - OFFSET TITULO
    INT 7 

LOOP:
    CALL INGRESAR_CARACTER
    INC CL
    CMP CL, 04H
    JZ RESULTADO
    JMP LOOP

RESULTADO:
    CMP AL, 00H
    JZ NEGAR_CLAVE
    MOV BX, OFFSET CLAVE_CORRECTA
    MOV AL, OFFSET CLAVE_INCORRECTA - OFFSET CLAVE_CORRECTA
    INT 7
    JMP FIN
    
NEGAR_CLAVE: 
    MOV BX, OFFSET CLAVE_INCORRECTA
    MOV AL, OFFSET CLAVE_FIN - OFFSET CLAVE_INCORRECTA
    INT 7

FIN: INT 0     
END
 