PIC EQU 20H 
EOI EQU 20H 
N_F10 EQU 10
  
 ORG 40 
IP_IMPRIMIR DW  IMPRIMIR_LETRA 

ORG 1000H
  LETRA DB "A"
  
 ORG 2000H 
 CLI 
 MOV AL, 0FEH; PORQUE IMPRIME CON FE? DEBERIA SER 7E PARA NO ENMASCARAR INT7
 OUT PIC+1, AL ; PIC: registro IMR 
 MOV AL, N_F10 
 OUT PIC+4, AL ; PIC: registro INT0 
 STI 
    MOV BX, OFFSET LETRA
LAZO:
    INC BYTE PTR [BX]

    CMP BYTE PTR [BX], 5AH; comparo con Z
    JNZ NO_RESETEAR_LETRA
    MOV BYTE PTR [BX], 41H; vuelvo a cargar A

NO_RESETEAR_LETRA:
    JMP LAZO 
  
 ORG 3000H 
IMPRIMIR_lETRA: PUSH AX 
    PUSH BX
    MOV BX, OFFSET LETRA
    MOV AL, 1
    INT 7
    MOV AL, EOI 
    OUT EOI, AL  ; PIC: registro EOI 
    POP BX
    POP AX 
    INT 0
    IRET
 END