ORG 1000H 
    MSJ   DB  "INGRESE UN NUMERO:" 
    FIN   DB  ? 
    CAR_INVALIDO DB "CARACTER NO VALIDO"
    FIN_CAR_INVALIDO DB ?
  
ORG 1500H 
    NUM   DB  ? 

ORG 3000H
ES_NUM: CMP BYTE PTR [BX], 30H
    JS ES_NUM_FAL
    CMP BYTE PTR [BX], 40H
    JNS ES_NUM_FAL
ES_NUM_VER: MOV AH, 0FFH
    RET
ES_NUM_FAL: MOV AH, 00H
    MOV BX, OFFSET CAR_INVALIDO
    MOV AL, OFFSET FIN_CAR_INVALIDO - OFFSET CAR_INVALIDO
    INT 7
    RET

  
ORG 2000H 
    MOV BX, OFFSET MSJ 
    MOV AL, OFFSET FIN-OFFSET MSJ 
    INT 7 
    MOV BX, OFFSET NUM 
    INT 6 
    MOV AL, 1 
    INT 7 
    MOV CL, NUM

    CALL ES_NUM
    
    INT 0 
END
 